### ISSUE TITLE
padding inconsistent with hyperborder plugin

### ISSUE THREAD

**Issue by unluisco** [henrikdahl/hyper-statusline#40]
Hi, without the hyperborder plugin, the padding is fine, but when I activate that plugin, the botton padding is affected:
![hyper 2017-03-03 15-05-18](https://cloud.githubusercontent.com/assets/6332263/23567186/1aa7fbb8-0023-11e7-99ff-f1b49aee5baa.png)
![hyper 2017-03-03 15-06-36](https://cloud.githubusercontent.com/assets/6332263/23567188/1f360710-0023-11e7-974d-c2304fc82c40.png)
By the way, this plugin is very good :)

**Comment by henrikdahl** [comment]
You're right. This will be adressed in future versions.

Been working on a PR for Hyper to expose the `hyper_main` properly so that the `hyper-statusline` footer can reside inside there instead of the root. That will also fix the padding issue with `hyperborder` and any similar plugins with related issues.

I'll keep this open until it's been merged ✌️

Thanks for your support!

**Comment by henrikdahl** [comment]
Latest release fixes the issue with padding ✌️
