### ISSUE TITLE
Icons path broken on Windows

### ISSUE THREAD

**Issue by Naramsim** [henrikdahl/hyper-statusline#6]
Hi, I am using Hyper v1.0.0 on my Win 10
The console shows this error: 
![screenshot 229](https://cloud.githubusercontent.com/assets/8996268/21183697/68685e54-c209-11e6-8b0d-164ee11e0cbb.png)

The path isn't correct
it should be: `file:///C:/Users/Ale/.hyper_plugins/node_modules/hyper-statusline/icons/dirty.svg`

**Comment by Naramsim** [comment]
I see that you use this call to inject the path:
```js
-webkit-mask-image: url('${__dirname}/icons/branch.svg');
```

if I `console.log(__dirname)` the result it gives me is `C:\Users\Ale\AppData\Local\hyper\app-1.0.0\resources\app`. There is no icons folder there.
![screenshot 230](https://cloud.githubusercontent.com/assets/8996268/21184212/add18da6-c20b-11e6-9ae2-cb8ab463798c.png)

**Comment by henrikdahl** [comment]
@Naramsim Mind trying if the icon path is fixed on the os-windows branch? I can't debug myself without Windows ✌️

**Comment by s2tephen** [comment]
Not sure if @henrikdahl merged this fix with master, but now icons aren't showing up for me on Mac OSX.

The CSS property is `-webkit-mask-image: url(./icons/folder.svg);` but for me that path points to `file:///Applications/Hyper.app/Contents/Resources/app/icons/folder.svg`, rather than looking in the `hyper_plugins/node_modules` folder.

**Comment by henrikdahl** [comment]
@s2tephen Was unintentional, tired mistake and tight schedule 😅

If you force an update it's been reverted.
